-- MySQL Script generated by MySQL Workbench
-- Tue Dec  5 09:31:23 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`User` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `is_admin` TINYINT NOT NULL,
  `username` VARCHAR(64) NOT NULL,
  `password` VARCHAR(32) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `username_UNIQUE` (`username` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Subject`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Subject` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `subject` VARCHAR(64) NOT NULL,
  `semester` INT NOT NULL,
  `year_of_study` INT NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Test`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Test` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `topic` VARCHAR(64) NOT NULL,
  `is_whole_semester` TINYINT NULL,
  `date` DATETIME NOT NULL,
  `Subject_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Test_Subject1_idx` (`Subject_id` ASC) VISIBLE,
  INDEX `fk_Test_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_Test_Subject1`
    FOREIGN KEY (`Subject_id`)
    REFERENCES `mydb`.`Subject` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Test_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TestHistory`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TestHistory` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `score` INT NOT NULL,
  `report` TEXT NULL,
  `date` DATETIME NOT NULL,
  `Test_id` INT NOT NULL,
  `User_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TestHistory_Test_idx` (`Test_id` ASC) VISIBLE,
  INDEX `fk_TestHistory_User1_idx` (`User_id` ASC) VISIBLE,
  CONSTRAINT `fk_TestHistory_Test`
    FOREIGN KEY (`Test_id`)
    REFERENCES `mydb`.`Test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_TestHistory_User1`
    FOREIGN KEY (`User_id`)
    REFERENCES `mydb`.`User` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`TestQuestion`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`TestQuestion` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `question` TEXT NOT NULL,
  `Test_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_TestQuestion_Test1_idx` (`Test_id` ASC) VISIBLE,
  CONSTRAINT `fk_TestQuestion_Test1`
    FOREIGN KEY (`Test_id`)
    REFERENCES `mydb`.`Test` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Answer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Answer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `answer` TEXT NOT NULL,
  `is_correct` TINYINT NOT NULL,
  `TestQuestion_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Answer_TestQuestion1_idx` (`TestQuestion_id` ASC) VISIBLE,
  CONSTRAINT `fk_Answer_TestQuestion1`
    FOREIGN KEY (`TestQuestion_id`)
    REFERENCES `mydb`.`TestQuestion` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
